crypto:
  - aixbt_agent
  - gemxbt_agent
  - wizardofsoho
  - KookCapitalLLC
  - insentos
  - blknoiz06
  - blancxbt
  - 0xkyle__
  - MinisterOfNFTs
  - alifarhat79
  - boldleonidas
  - TylerDurden
  - 0xStari
  - watchking69